// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TMmvc.Data;

namespace TMmvc.Migrations
{
    [DbContext(typeof(TMContext))]
    [Migration("20201206092347_StartDb")]
    partial class StartDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TMmvc.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActivityTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("End")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Start")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivityTypeId");

                    b.ToTable("Activity");
                });

            modelBuilder.Entity("TMmvc.Models.ActivityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ActivityType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsExternal = false,
                            Name = "Generico"
                        },
                        new
                        {
                            Id = 2,
                            IsExternal = false,
                            Name = "Sport"
                        },
                        new
                        {
                            Id = 3,
                            IsExternal = false,
                            Name = "Consulenza"
                        },
                        new
                        {
                            Id = 4,
                            IsExternal = false,
                            Name = "Studio"
                        },
                        new
                        {
                            Id = 5,
                            IsExternal = false,
                            Name = "Casa"
                        });
                });

            modelBuilder.Entity("TMmvc.Models.Activity", b =>
                {
                    b.HasOne("TMmvc.Models.ActivityType", "ActivityType")
                        .WithMany()
                        .HasForeignKey("ActivityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityType");
                });
#pragma warning restore 612, 618
        }
    }
}
